# Generated by Django 4.0 on 2022-09-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pdca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=20)),
                ('memo', models.TextField(null=True)),
                ('deadline', models.DateField()),
                ('p', models.TextField()),
                ('d', models.TextField(null=True)),
                ('c', models.TextField(null=True)),
                ('a', models.TextField(null=True)),
                ('weight', models.IntegerField(choices=[(1, 'Light'), (2, 'Middle'), (3, 'Heavy')], null=True)),
                ('comment', models.TextField(null=True)),
                ('condition', models.IntegerField(blank=True, choices=[(1, 'Preparation'), (2, 'Open'), (3, 'Close')], default='', null=True)),
                ('tag_name', models.ManyToManyField(blank=True, default='', null=True, to='mach_pdca_app.Tag')),
                ('user_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mach_pdca_app.user')),
            ],
        ),
    ]
