# Generated by Django 4.0 on 2022-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mach_pdca_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdcamodel',
            name='Memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdcamodel',
            name='a',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdcamodel',
            name='c',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdcamodel',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdcamodel',
            name='d',
            field=models.TextField(null=True),
        ),
    ]
