# Generated by Django 4.0 on 2022-08-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mach_pdca_app', '0003_alter_condition_condition_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcamodel',
            name='condition',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mach_pdca_app.condition'),
        ),
        migrations.AddField(
            model_name='pdcamodel',
            name='tag_name',
            field=models.ManyToManyField(blank=True, default='', null=True, to='mach_pdca_app.Tag'),
        ),
    ]
