# Generated by Django 4.0 on 2022-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mach_pdca_app', '0006_alter_condition_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
