# Generated by Django 4.0 on 2022-08-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mach_pdca_app', '0007_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='pdca_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='pdca_id',
        ),
    ]
