# Generated by Django 4.0 on 2022-08-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mach_pdca_app', '0008_remove_condition_pdca_id_remove_tag_pdca_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdcamodel',
            name='user_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mach_pdca_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
